// <auto-generated />
using System;
using Appman.LeaveManagement.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Appman.LeaveManagement.Migrations
{
    [DbContext(typeof(LeaveManagementDbContext))]
    [Migration("20180713072724_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.Approbation", b =>
                {
                    b.Property<Guid>("ApprobationGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApproverId");

                    b.Property<int>("LeaveId");

                    b.Property<string>("Status");

                    b.HasKey("ApprobationGuid");

                    b.ToTable("Approbations");
                });

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.Employee", b =>
                {
                    b.Property<string>("StaffId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("GenderCode");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsInProbation");

                    b.Property<bool>("IsSuperHr");

                    b.Property<string>("LastName");

                    b.Property<string>("Position");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("Section");

                    b.Property<DateTime>("StartWorkingDate");

                    b.HasKey("StaffId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.LeaveInfo", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovalStatus");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedTime");

                    b.Property<string>("AttachedFile1");

                    b.Property<string>("AttachedFile2");

                    b.Property<string>("AttachedFile3");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("HoursEndDate");

                    b.Property<int>("HoursStartDate");

                    b.Property<DateTime>("RequestedDateTime");

                    b.Property<string>("StaffId");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("Type");

                    b.HasKey("LeaveId");

                    b.ToTable("LeaveInfos");
                });

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.MdGender", b =>
                {
                    b.Property<string>("GenderCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EN");

                    b.Property<string>("TH");

                    b.HasKey("GenderCode");

                    b.ToTable("MdGenders");
                });

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.RemainingHour", b =>
                {
                    b.Property<string>("StaffId");

                    b.Property<string>("Year");

                    b.Property<int>("AnnualHours");

                    b.Property<int>("LWPHours");

                    b.Property<int>("SickHours");

                    b.HasKey("StaffId", "Year");

                    b.ToTable("RemainingHours");
                });

            modelBuilder.Entity("Appman.LeaveManagement.DatabaseContext.Model.Reporting", b =>
                {
                    b.Property<string>("StaffId");

                    b.Property<string>("Approver");

                    b.HasKey("StaffId", "Approver");

                    b.ToTable("Reportings");
                });
#pragma warning restore 612, 618
        }
    }
}
