// <auto-generated />
using System;
using LeaveManagement.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeaveManagement.Migrations
{
    [DbContext(typeof(LeaveManagementDbContext))]
    partial class LeaveManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.Approbation", b =>
                {
                    b.Property<Guid>("ApprobationGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApproverId");

                    b.Property<int>("LeaveId");

                    b.Property<string>("Status");

                    b.HasKey("ApprobationGuid");

                    b.ToTable("Approbations");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstNameEN");

                    b.Property<string>("FirstNameTH");

                    b.Property<string>("GenderCode");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsNotified");

                    b.Property<string>("LastNameEN");

                    b.Property<string>("LastNameTH");

                    b.Property<string>("Nickname");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("RoleCode");

                    b.Property<string>("StaffId");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.LeaveInfo", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovalStatus");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedTime");

                    b.Property<string>("AttachedFile1");

                    b.Property<string>("AttachedFile2");

                    b.Property<string>("AttachedFile3");

                    b.Property<string>("AttachedFileName1");

                    b.Property<string>("AttachedFileName2");

                    b.Property<string>("AttachedFileName3");

                    b.Property<string>("Comment");

                    b.Property<string>("CommentByAdmin");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("HoursEndDate");

                    b.Property<int>("HoursStartDate");

                    b.Property<bool>("IsExisting");

                    b.Property<DateTime>("RequestedDateTime");

                    b.Property<string>("StaffId");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("Type");

                    b.HasKey("LeaveId");

                    b.ToTable("LeaveInfos");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.MdGender", b =>
                {
                    b.Property<string>("GenderCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenderEN");

                    b.Property<string>("GenderTH");

                    b.Property<string>("TitleEN");

                    b.Property<string>("TitleTH");

                    b.HasKey("GenderCode");

                    b.ToTable("MdGenders");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.MdRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Department");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsInProbation");

                    b.Property<string>("Position");

                    b.HasKey("RoleCode");

                    b.ToTable("MdRoles");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.RemainingHour", b =>
                {
                    b.Property<string>("StaffId");

                    b.Property<string>("Year");

                    b.Property<int>("AnnualHours");

                    b.Property<int>("LWPHours");

                    b.Property<int>("SickHours");

                    b.Property<int>("TotalAnnualHours");

                    b.Property<int>("TotalSickHours");

                    b.HasKey("StaffId", "Year");

                    b.ToTable("RemainingHours");
                });

            modelBuilder.Entity("LeaveManagement.DatabaseContext.Model.Reporting", b =>
                {
                    b.Property<string>("StaffId");

                    b.Property<string>("Approver");

                    b.HasKey("StaffId", "Approver");

                    b.ToTable("Reportings");
                });
#pragma warning restore 612, 618
        }
    }
}
